import "./globals.css";
import Header from "./components/NewCV/Header";

export const metadata = {
  title: 'Learning Next.js with Ben BK',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
